### ISSUE TITLE
Error while building DKMS on ArchLinux ARM with Linux 6.1.14

### ISSUE THREAD

**Issue by aabdellah** [dereference23/notwireguard-linux-compat#5]
`==> dkms install --no-depmod notwireguard/1.0.20220627 -k 6.1.14-1-rpi-ARCH
Error! Bad return status for module build on kernel: 6.1.14-1-rpi-ARCH (aarch64)
Consult /var/lib/dkms/notwireguard/1.0.20220627/build/make.log for more information.
==> WARNING: `dkms install --no-depmod notwireguard/1.0.20220627 -k 6.1.14-1-rpi-ARCH' exited 10`

`DKMS make.log for notwireguard-1.0.20220627 for kernel 6.1.14-1-rpi-ARCH (aarch64)
Fri Mar  3 04:52:37 PM EET 2023
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: aarch64-unknown-linux-gnu-gcc (GCC) 12.1.0
  You are using:           gcc (GCC) 12.1.0
/var/lib/dkms/notwireguard/1.0.20220627/build/peer.c: In function ‘wg_peer_create’:
/var/lib/dkms/notwireguard/1.0.20220627/build/peer.c:57:9: error: too many arguments to function ‘netif_napi_add’
   57 |         netif_napi_add(wg->dev, &peer->napi, wg_packet_rx_poll,
      |         ^~~~~~~~~~~~~~
In file included from ./include/net/sock.h:46,
                 from ./include/linux/tcp.h:19,
                 from ./include/linux/ipv6.h:93,
                 from /var/lib/dkms/notwireguard/1.0.20220627/build/allowedips.h:11,
                 from /var/lib/dkms/notwireguard/1.0.20220627/build/device.h:10,
                 from /var/lib/dkms/notwireguard/1.0.20220627/build/peer.h:9,
                 from /var/lib/dkms/notwireguard/1.0.20220627/build/peer.c:6:
./include/linux/netdevice.h:2569:1: note: declared here
 2569 | netif_napi_add(struct net_device *dev, struct napi_struct *napi,
      | ^~~~~~~~~~~~~~
make[1]: *** [scripts/Makefile.build:250: /var/lib/dkms/notwireguard/1.0.20220627/build/peer.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:2005: /var/lib/dkms/notwireguard/1.0.20220627/build] Error 2`
