### ISSUE TITLE
Build error on Archlinux ARM aarch64

### ISSUE THREAD

**Issue by aabdellah** [dereference23/notwireguard-linux-compat#1]
There seems to be an error when building DKMS modules on aarch64 kernels like on the raspberry pi, details below:

```
(1/1) installing notwireguard-dkms                                       [########################################] 100%
:: Running post-transaction hooks...
(1/2) Arming ConditionNeedsUpdate...
(2/2) Install DKMS modules
==> dkms install --no-depmod notwireguard/1.0.20211208 -k 5.10.83-1-rpi-ARCH
Error! Bad return status for module build on kernel: 5.10.83-1-rpi-ARCH (aarch64)
Consult /var/lib/dkms/notwireguard/1.0.20211208/build/make.log for more information.
==> WARNING: `dkms install --no-depmod notwireguard/1.0.20211208 -k 5.10.83-1-rpi-ARCH' exited 10
```

Here's make.log:
```
DKMS make.log for notwireguard-1.0.20211208 for kernel 5.10.83-1-rpi-ARCH (aarch64)
Tue Dec 14 02:42:53 PM EET 2021
make: Entering directory '/usr/lib/modules/5.10.83-1-rpi-ARCH/build'
  CC [M]  /var/lib/dkms/notwireguard/1.0.20211208/build/main.o
  CC [M]  /var/lib/dkms/notwireguard/1.0.20211208/build/noise.o
  CC [M]  /var/lib/dkms/notwireguard/1.0.20211208/build/device.o
  CC [M]  /var/lib/dkms/notwireguard/1.0.20211208/build/peer.o
/var/lib/dkms/notwireguard/1.0.20211208/build/device.c:230:21: error: ‘dev_get_tstats64’ undeclared here (not in a function); did you mean ‘dev_get_stats’?
  230 |  .ndo_get_stats64 = dev_get_tstats64
      |                     ^~~~~~~~~~~~~~~~
      |                     dev_get_stats
make[1]: *** [scripts/Makefile.build:280: /var/lib/dkms/notwireguard/1.0.20211208/build/device.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:1825: /var/lib/dkms/notwireguard/1.0.20211208/build] Error 2
make: Leaving directory '/usr/lib/modules/5.10.83-1-rpi-ARCH/build'
```

Kernel version:
Linux pi 5.10.83-1-rpi-ARCH #1 SMP PREEMPT Tue Dec 7 15:21:39 UTC 2021 aarch64 GNU/Linux

**Comment by dereference23** [comment]
Try this one

https://transfer.sh/XABzms/notwireguard-dkms_1.0.20211208_all.deb

**Comment by aabdellah** [comment]
> Try this one
> 
> https://transfer.sh/XABzms/notwireguard-dkms_1.0.20211208_all.deb

I'm using Archlinux ARM.

**Comment by dereference23** [comment]
> > Try this one
> > https://transfer.sh/XABzms/notwireguard-dkms_1.0.20211208_all.deb
> 
> I'm using Archlinux ARM.

Ooops, my bad. I've pushed the commit.

**Comment by aabdellah** [comment]
Thanks!

makepkg worked after latest commit, I think it would be a good idea to add 'aarch64' to the PKGBUILD as well.

**Comment by dereference23** [comment]
> I think it would be a good idea to add 'aarch64' to the PKGBUILD as well.

Done
