### ISSUE TITLE
Build failure while installing DKMS module after kernel update

### ISSUE THREAD

**Issue by aabdellah** [dereference23/notwireguard-linux-compat#2]
After updating the kernel using pacman on Arch Linux to 5.10.88, the following error was shown on "install DKMS modules" phase:

```(12/17) Install DKMS modules                                                                                                                                                                    
==> dkms install --no-depmod notwireguard/1.0.20211208 -k 5.10.88-1-rpi-ARCH                                                                                                                    
Error! Bad return status for module build on kernel: 5.10.88-1-rpi-ARCH (aarch64)                                                                                                               
Consult /var/lib/dkms/notwireguard/1.0.20211208/build/make.log for more information.                                                                                                            
==> WARNING: `dkms install --no-depmod notwireguard/1.0.20211208 -k 5.10.88-1-rpi-ARCH' exited 10```

make.log output:
```DKMS make.log for notwireguard-1.0.20211208 for kernel 5.10.88-1-rpi-ARCH (aarch64)
Fri Dec 31 12:47:29 AM EET 2021
make: Entering directory '/usr/lib/modules/5.10.88-1-rpi-ARCH/build'
  CC [M]  /var/lib/dkms/notwireguard/1.0.20211208/build/main.o
  CC [M]  /var/lib/dkms/notwireguard/1.0.20211208/build/noise.o
  CC [M]  /var/lib/dkms/notwireguard/1.0.20211208/build/device.o
  CC [M]  /var/lib/dkms/notwireguard/1.0.20211208/build/peer.o
In file included from <command-line>:
/var/lib/dkms/notwireguard/1.0.20211208/build/compat/compat.h:1141:20: error: static declaration of ‘dst_cache_reset_now’ follows non-static declaration
 1141 | static inline void dst_cache_reset_now(struct dst_cache *dst_cache)
      |                    ^~~~~~~~~~~~~~~~~~~
In file included from /var/lib/dkms/notwireguard/1.0.20211208/build/compat/compat.h:1130,
                 from <command-line>:
./include/net/dst_cache.h:91:6: note: previous declaration of ‘dst_cache_reset_now’ was here
   91 | void dst_cache_reset_now(struct dst_cache *dst_cache);
      |      ^~~~~~~~~~~~~~~~~~~
In file included from <command-line>:
/var/lib/dkms/notwireguard/1.0.20211208/build/compat/compat.h:1141:20: error: static declaration of ‘dst_cache_reset_now’ follows non-static declaration
 1141 | static inline void dst_cache_reset_now(struct dst_cache *dst_cache)
      |                    ^~~~~~~~~~~~~~~~~~~
In file included from /var/lib/dkms/notwireguard/1.0.20211208/build/compat/compat.h:1130,
                 from <command-line>:
./include/net/dst_cache.h:91:6: note: previous declaration of ‘dst_cache_reset_now’ was here
   91 | void dst_cache_reset_now(struct dst_cache *dst_cache);
      |      ^~~~~~~~~~~~~~~~~~~
make[1]: *** [scripts/Makefile.build:280: /var/lib/dkms/notwireguard/1.0.20211208/build/peer.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from <command-line>:
/var/lib/dkms/notwireguard/1.0.20211208/build/compat/compat.h:1141:20: error: static declaration of ‘dst_cache_reset_now’ follows non-static declaration
 1141 | static inline void dst_cache_reset_now(struct dst_cache *dst_cache)
      |                    ^~~~~~~~~~~~~~~~~~~
In file included from /var/lib/dkms/notwireguard/1.0.20211208/build/compat/compat.h:1130,
                 from <command-line>:
./include/net/dst_cache.h:91:6: note: previous declaration of ‘dst_cache_reset_now’ was here
   91 | void dst_cache_reset_now(struct dst_cache *dst_cache);
      |      ^~~~~~~~~~~~~~~~~~~
make[1]: *** [scripts/Makefile.build:280: /var/lib/dkms/notwireguard/1.0.20211208/build/noise.o] Error 1
In file included from <command-line>:
/var/lib/dkms/notwireguard/1.0.20211208/build/compat/compat.h:1141:20: error: static declaration of ‘dst_cache_reset_now’ follows non-static declaration
 1141 | static inline void dst_cache_reset_now(struct dst_cache *dst_cache)
      |                    ^~~~~~~~~~~~~~~~~~~
In file included from /var/lib/dkms/notwireguard/1.0.20211208/build/compat/compat.h:1130,
                 from <command-line>:
./include/net/dst_cache.h:91:6: note: previous declaration of ‘dst_cache_reset_now’ was here
   91 | void dst_cache_reset_now(struct dst_cache *dst_cache);
      |      ^~~~~~~~~~~~~~~~~~~
make[1]: *** [scripts/Makefile.build:280: /var/lib/dkms/notwireguard/1.0.20211208/build/device.o] Error 1
make[1]: *** [scripts/Makefile.build:280: /var/lib/dkms/notwireguard/1.0.20211208/build/main.o] Error 1
make: *** [Makefile:1825: /var/lib/dkms/notwireguard/1.0.20211208/build] Error 2
make: Leaving directory '/usr/lib/modules/5.10.88-1-rpi-ARCH/build'
```

Package was created by `makepkg -si` on HEAD tree.

**Comment by dereference23** [comment]
Sorry for delay. Should be fixed now

**Comment by aabdellah** [comment]
Thanks, working good now.
